services:
  gpt:
    image: gpt:latest
    container_name: gpt
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "none"
    platform: linux/x86_64
    tty: true
    volumes:
       - ./data:/root/practiceGPT4AllRAG/data:r
    restart: always
    command: /bin/bash
